# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ryan Cullum
email: racullum@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Software Engineer - Game Developer - Life Long Learner
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://racullum.github.io" # the base hostname & protocol for your site

# Social media profiles - feel free to add more here
github_username:  Racullum
#instagram_username: beyonce
#stackoverflow_url: https://
#googleplus_username: BobMarley
#skype_username: echo123
linkedin_url: https://www.linkedin.com/in/ryancullum/

# Address information
address_city: Kansas City
address_state: MO
address_zip: 64105

# Build settings
markdown: kramdown
